name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  ci:
    name: Dev Container CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Run Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: docgraph-dev
          cacheFrom: docgraph-dev
          push: never
          runCmd: |
            cargo fmt -- --check
            cargo clippy -- -D warnings
            cargo audit
            npm install --prefix vsix
            npm run lint --prefix vsix
            cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
            cargo run -- check ./doc
